"""Constants to be used throughout."""

import os

SPLITWISE_CONSUMER_KEY = os.getenv("SPLITWISE_CONSUMER_KEY", None)
SPLITWISE_CONSUMER_SECRET = os.getenv("SPLITWISE_CONSUMER_SECRET", None)
SPLITWISE_ACCESS_TOKEN = os.getenv("SPLITWISE_ACCESS_TOKEN", None)
SPLITWISE_ACCESS_TOKEN_SECRET = os.getenv("SPLITWISE_ACCESS_TOKEN_SECRET", None)
SPLITWISE_GROUP_ID = os.getenv("SPLITWISE_GROUP_ID", None)
SPLITWISE_USER_ID_BRAM = os.getenv("SPLITWISE_USER_ID_BRAM", None)
SPLITWISE_USER_ID_ANNE = os.getenv("SPLITWISE_USER_ID_ANNE", None)
BASE_URL = os.getenv("BASE_URL", None)
API_ACCESS_TOKEN = os.getenv("API_ACCESS_TOKEN", None)
